### ISSUE TITLE
Can't compile due to undefined variable

### ISSUE THREAD

**Issue by MrButlerTron** [frux-c/uhf_rfid#6]
I attempted to compile this with ufbt and fbt, both times I get the error that  `'FontBatteryPercent' undeclared` .
on line 84 in file uhf_scene_device_info.c
I tried to search through the code as well as the Flipper firmware code for a similarly named variable and could not find it.  

This seems to prevent compilation.

Am I missing a step or is there an easy fix to this?

**Comment by frux-c** [comment]
Which branch did you try to compile?

**Comment by MrButlerTron** [comment]
I think master, I didn't notice there were others.
Which one would you recommend?

**Comment by frux-c** [comment]
Master is fine.

Change the font from `FontBatteryPercent` to a different font like `FontKeyboard`, and see if that works.
If that doesn't work, maybe try importing `<canvas.h>` temporarly in the `uhf_app_i.h` file.

**Comment by MrButlerTron** [comment]
Changing it to `FontKeyboard` allows it to compile.  Thank you.
